name: PHP Unit Tests

on:
  push:
    branches:
      - master
      - release/*
  pull_request:

jobs:
  unit-php:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental == true }}
    strategy:
      matrix:
        php: ['7.4', '7.0', '5.6']
        wp: ['latest']
        include:
          - php: '8.0'
            wp: 'trunk'
            experimental: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mysql
          coverage: xdebug
          tools: composer, cs2pr

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Setup Composer cache
        uses: pat-s/always-upload-cache@v1.1.4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
            ${{ runner.os }}-

      - name: Install dependencies
        run: composer install --prefer-dist --no-suggest --no-progress --no-interaction

      - name: Start Docker environment
        run: npm run wp-env start
        env:
          COMPOSE_INTERACTIVE_NO_CLI: true

      - name: Run tests
        run: npm run test:php
        if: ${{ matrix.wp != 'latest' || matrix.php != 7.4 }}

      - name: Run tests with coverage
        run: npm run test:php -- --coverage-clover build/logs/clover.xml
        if: ${{ matrix.wp == 'latest' && matrix.php == 7.4 }}

      - name: Uplaod code coverage report
        uses: codecov/codecov-action@v1
        with:
          file: build/logs/clover.xml
        if: ${{ matrix.wp == 'latest' && matrix.php == 7.4 }}
